// Generated by platform/kv260/scripts/generate_memory_map.py; do not edit.
// Source: memory_map.json
package z486_kv260_memory_map_pkg;
    localparam logic [31:0] CMA_SIZE = 32'h10000000;
    localparam logic [31:0] GUEST_OFFSET = 32'h00000000;
    localparam logic [31:0] GUEST_SIZE   = 32'h08000000;
    localparam logic [31:0] RESERVED0_OFFSET = 32'h08000000;
    localparam logic [31:0] RESERVED0_SIZE   = 32'h02000000;
    localparam logic [31:0] ZSST_FBI_OFFSET = 32'h0a000000;
    localparam logic [31:0] ZSST_FBI_SIZE   = 32'h00800000;
    localparam logic [31:0] ZSST_TMU_OFFSET = 32'h0a800000;
    localparam logic [31:0] ZSST_TMU_SIZE   = 32'h00800000;
    localparam logic [31:0] RESERVED_OFFSET = 32'h0b000000;
    localparam logic [31:0] RESERVED_SIZE   = 32'h04800000;
    localparam logic [31:0] PACKED_VGA_OFFSET = 32'h0f800000;
    localparam logic [31:0] PACKED_VGA_SIZE   = 32'h00800000;
endpackage
