#!/usr/bin/env python3
"""Generate the shared KV260 CMA layout for RTL and Linux software."""

import argparse
import json
from pathlib import Path


def number(value):
    return int(value, 0) if isinstance(value, str) else int(value)


def macro(name):
    return name.upper().replace("-", "_")


def validate(layout):
    cma_size = number(layout["cma_size"])
    cursor = 0
    names = set()
    for region in layout["regions"]:
        name = region["name"]
        offset = number(region["offset"])
        size = number(region["size"])
        if name in names:
            raise ValueError(f"duplicate region {name}")
        if offset != cursor:
            raise ValueError(f"gap or overlap before {name}: {offset:#x} != {cursor:#x}")
        if offset & 0xfffff or size == 0 or size & 0xfffff:
            raise ValueError(f"region {name} is not MiB aligned")
        names.add(name)
        cursor += size
    if cursor != cma_size:
        raise ValueError(f"regions end at {cursor:#x}, CMA ends at {cma_size:#x}")


def render_c(layout, source):
    lines = [
        "/* Generated by platform/kv260/scripts/generate_memory_map.py; do not edit. */",
        f"/* Source: {source.name} */",
        "#ifndef Z486_KV260_MEMORY_MAP_H",
        "#define Z486_KV260_MEMORY_MAP_H",
        "",
        f"#define Z486_KV260_CMA_SIZE 0x{number(layout['cma_size']):08x}U",
    ]
    for region in layout["regions"]:
        name = macro(region["name"])
        lines.append(f"#define Z486_KV260_{name}_OFFSET 0x{number(region['offset']):08x}U")
        lines.append(f"#define Z486_KV260_{name}_SIZE   0x{number(region['size']):08x}U")
    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def render_sv(layout, source):
    lines = [
        "// Generated by platform/kv260/scripts/generate_memory_map.py; do not edit.",
        f"// Source: {source.name}",
        "package z486_kv260_memory_map_pkg;",
        f"    localparam logic [31:0] CMA_SIZE = 32'h{number(layout['cma_size']):08x};",
    ]
    for region in layout["regions"]:
        name = macro(region["name"])
        lines.append(f"    localparam logic [31:0] {name}_OFFSET = 32'h{number(region['offset']):08x};")
        lines.append(f"    localparam logic [31:0] {name}_SIZE   = 32'h{number(region['size']):08x};")
    lines.extend(["endpackage", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("c_header", type=Path)
    parser.add_argument("sv_package", type=Path)
    args = parser.parse_args()
    layout = json.loads(args.source.read_text())
    validate(layout)
    args.c_header.parent.mkdir(parents=True, exist_ok=True)
    args.sv_package.parent.mkdir(parents=True, exist_ok=True)
    args.c_header.write_text(render_c(layout, args.source))
    args.sv_package.write_text(render_sv(layout, args.source))


if __name__ == "__main__":
    main()
