BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "z486-xl"
BBFILE_PATTERN_z486-xl = "^${LAYERDIR}/"
BBFILE_PRIORITY_z486-xl = "10"
LAYERSERIES_COMPAT_z486-xl = "scarthgap"
LAYERDEPENDS_z486-xl = "core"
